rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
before_install:
  - gem update --system
  - gem --version
script: "bundle exec rake test"
jdk:
  - openjdk6
gemfile:
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_0.gemfile
